import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../src/app.js';import {seed} from '../src/store.js';
test('API enforces task ownership, completion notes, private chat and directory roles',async t=>{const db=seed();const app=createApp({db,save(){}});const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port+'/api';
 const call=async(path,method='GET',body,token)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}};
 const login=async(username)=>(await call('/login','POST',{username,password:'ITunit-demo-2026!'})).data.token;
 const sdd=await login('itunit1'),insaf=await login('itunit2'),damith=await login('itunit3'),admin=await login('admin');
 assert.equal((await call('/workspace')).status,401);
 assert.equal((await call('/tasks/t0','PATCH',{status:'Completed',note:'done'},damith)).status,403);
 assert.equal((await call('/tasks/t0','PATCH',{status:'Completed'},insaf)).status,400);
 assert.equal((await call('/tasks/t0','PATCH',{status:'Completed',note:'Network restored'},insaf)).status,200);
 assert.equal(db.tasks[0].completedBy,'u1');assert.equal(db.tasks[0].progress,100);
 assert.equal((await call('/tasks/t0','PATCH',{status:'Assigned',note:'Recheck'},insaf)).status,403);
 assert.equal((await call('/tasks/t0','PATCH',{status:'Assigned',note:'Recheck'},sdd)).status,200);
 assert.equal((await call('/tasks/t0','PATCH',{assignee:'u2'},sdd)).status,200);
 assert.equal((await call('/tasks/t0','PATCH',{progress:50},insaf)).status,403);
 const c=(await call('/conversations','POST',{member:'u1'},sdd)).data;
 assert.equal((await call('/messages','POST',{conversation:c.id,body:'Private'},sdd)).status,201);
 assert.equal((await call('/messages','POST',{conversation:c.id,body:'Intrusion'},damith)).status,403);
 assert.equal((await call('/workspace','GET',undefined,damith)).data.messages.some(m=>m.conversation===c.id),false);
 assert.equal((await call('/users/u1','PATCH',{name:'Changed'},insaf)).status,403);
 assert.equal((await call('/users/u1','PATCH',{role:'admin'},sdd)).status,403);
 assert.equal((await call('/users/u1','PATCH',{username:'newname'},insaf)).status,403);
 assert.equal((await call('/users/u11','PATCH',{username:'newadmin'},sdd)).status,403);
 for(const username of ['', 'bad name','x'.repeat(201)])assert.equal((await call('/users/u1','PATCH',{username},sdd)).status,400);
 assert.equal((await call('/users/u1','PATCH',{username:'ITUNIT3',name:'Should not change'},sdd)).status,409);
 assert.equal(db.users.find(u=>u.id==='u1').name,'Mr. Insaf');
 assert.equal((await call('/users/u1','PATCH',{username:'itunit20'},sdd)).status,200);
 assert.equal((await call('/login','POST',{username:'itunit2',password:'ITunit-demo-2026!'})).status,401);
 assert.equal((await call('/login','POST',{username:'itunit20',password:'ITunit-demo-2026!'})).status,200);
 assert.equal((await call('/users/u1','PATCH',{username:'itunit21'},admin)).status,200);
 assert.equal((await call('/users/u1','PATCH',{username:'itunit21'},admin)).status,200);
 assert.equal(db.audit.filter(a=>a.action==='member.username_changed').length,2);
 assert.equal((await call('/tasks/t0','DELETE',undefined,sdd)).status,403);
 assert.equal((await call('/tasks/t0','DELETE',undefined,admin)).status,200);assert.equal(db.tasks[0].deleted,true);
 assert.equal((await call('/users/u2','PATCH',{active:false},sdd)).status,200);
 assert.equal((await call('/workspace','GET',undefined,damith)).status,401);
});
