import {canManage,canWork,publicUser,hash,id,now,divisions} from '../store.js';
export function registerMeetingsRoutes(app,context){
 const {db,save,error,text,note,audit}=context;
 app.put('/api/meetings/:id',async (req,res)=>{if(!canManage(req.user))return error(res,403,'Meeting management access required');const m=db.meetings.find(m=>m.id===req.params.id);if(!m)return error(res,404,'Meeting not found');const b=req.body;if(!text(b.title)||!Number.isFinite(Date.parse(b.start)))return error(res,400,'Enter a title and valid date');m.title=text(b.title);m.agenda=text(b.agenda,4000);m.location=text(b.location,500);m.start=new Date(b.start).toISOString();note(m.attendees,'Meeting updated',m.title);audit(req.user,'meeting.updated',m.id);await save();res.json(m)});
 app.delete('/api/meetings/:id',async (req,res)=>{if(req.user.role!=='admin')return error(res,403,'Administrator access required');const m=db.meetings.find(m=>m.id===req.params.id);if(!m)return error(res,404,'Meeting not found');note(m.attendees,'Meeting removed',m.title);db.meetings=db.meetings.filter(m=>m.id!==req.params.id);audit(req.user,'meeting.removed',m.id);await save();res.json({ok:true})});
 app.post('/api/meetings',async (req,res)=>{if(!canManage(req.user))return error(res,403,'Only the SDD or administrator can schedule meetings');const b=req.body;if(!text(b.title)||!Number.isFinite(Date.parse(b.start))||!Array.isArray(b.attendees)||!b.attendees.length||b.attendees.some(x=>!db.users.some(u=>u.id===x&&u.active)))return error(res,400,'Enter a title, valid date and attendees');const m={id:id(),title:text(b.title),agenda:text(b.agenda,4000),start:new Date(b.start).toISOString(),location:text(b.location,500),attendees:b.attendees,responses:{},createdBy:req.user.id,cancelled:false};db.meetings.push(m);note(m.attendees,'Meeting invitation',m.title);audit(req.user,'meeting.created',m.id);await save();res.status(201).json(m)});
 app.patch('/api/meetings/:id',async (req,res)=>{const m=db.meetings.find(m=>m.id===req.params.id);if(!m)return error(res,404,'Meeting not found');if(req.body.cancelled===true){if(!canManage(req.user))return error(res,403,'Organizer access required');m.cancelled=true;note(m.attendees,'Meeting cancelled',m.title)}else {if(!m.attendees.includes(req.user.id)||!['Accepted','Declined'].includes(req.body.response))return error(res,403,'Invalid attendance response');m.responses[req.user.id]=req.body.response}await save();res.json(m)});
}

